routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('product_categories', 'ProductCategoriesController');
Route::resource('sub_categories', 'ProductSubCategoriesController');
Route::resource('brands', 'BrandsController');
Route::resource('products', 'ProductsController');
Route::resource('markets', 'MarketsController');
Route::resource('vendors', 'VendorsController');
Route::resource('category', 'CategoryProductsController');

Route::resource('market', 'ShopMarketsController');

Route::get('/fruits', 'CategoryProductsController@show_fruits')->name('fruits');
Route::get('/vegetables', 'CategoryProductsController@show_vegetables')->name('vegetables');
Route::get('/meats', 'CategoryProductsController@show_meats')->name('meats');
Route::get('/potatoes', 'CategoryProductsController@show_potatoes')->name('potatoes');

// Markets
// Route::get('sessions', 'SessionsController');

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::resource('shop', 'ShopController');
Route::get('computers_network_eqpt', 'ShopController@ict_solutions')->name('comps_network_eqpt');
Route::get('power_solutions', 'ShopController@power_solutions')->name('power_solutions');
Route::get('security_solutions', 'ShopController@security_solutions')->name('security_solutions');

// Routes for products per category
Route::get('computers_network_eqpt/{identifier}', 'ShopController@ict_products')->name('comps_network_eqpt_products');
Route::get('power_solutions/{identifier}', 'ShopController@power_products')->name('power_products');
Route::get('security_solutions/{identifier}', 'ShopController@security_products')->name('security_products');

Auth::routes(['verified' => false]);

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::get('customer/sign_up', 'Customer\Auth\RegisterController@customerRegistrationForm')->name('customer.register');
Route::post('customer/register', 'Customer\Auth\RegisterController@create')->name('customer.create');
Route::get('customer/profile', 'CustomerProfileController@profile')->name('customer.profile');
Route::get('customer/profile/edit/{token}', 'CustomerProfileController@edit')->name('customer.profile.edit');
Route::put('customer/profile/update/{token}', 'CustomerProfileController@update')->name('customer.profile.update');

Route::prefix('/customer')->name('customer.')->namespace('Customer')->group(function () {

    // Route::get('/profile', function(){
    //     return view('customer/profile');
    // })->name('profile');


    // All the customer routes will be defined here...
    Route::namespace('Auth')->group(function () {

        // Login Routes
        Route::get('/login', 'LoginController@showLoginForm')->name('login');
        Route::post('/login', 'LoginController@login');
        Route::post('/logout', 'LoginController@logout')->name('logout');

        // Forgot Password Routes
        Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        // Reset Password Routes
        Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    });
});

// Store Front

Route::resource('items', 'ItemsController');

Route::post('cart-add', 'CartController@add')->name('cart.add');
Route::get('cart', 'CartController@cart')->name('cart');
Route::get('cart-clear', 'CartController@clear')->name('cart.clear');
Route::post('cart-increase-qty', 'CartController@cart_increase_qty')->name('cart.increase_qty');
Route::put('cart-update/{token}', 'CartController@update')->name('cart.update');
Route::post('update-cart', 'CartController@update_cart')->name('update.cart');

Route::get('sub_category_related_products', 'AjaxController@get_products_per_sub_category')->name('products_per_sub_category');
Route::get('category_related_sub_categories', 'AjaxController@get_sub_categories_per_category')->name('sub_categories_per_category');
Route::get('areas_per_region', 'AjaxController@areas_per_region')->name('areas_per_region');
Route::post('change_featured_status', 'AjaxController@change_featured_status');
Route::get('sub_categories_per_product_category', 'AjaxController@get_sub_categories_per_product_category')->name('sub_categories_per_product_category');

Route::get('add_icon', 'CategoryIconsController@add_icon')->name('category.add_icon');
Route::post('store_icon', 'CategoryIconsController@store_icon')->name('category.store_icon');

Route::get('successful_order', 'PagesController@order_success')->name('order.success');

// ORDER PROCESSING
Route::get('process_order/{token}', 'OrderDeliveryController@process_order')->name('process_order');
Route::post('process_order_delivery', 'OrderDeliveryController@process_order_delivery')->name('process_order_delivery');
Route::post('dispatch_order', 'OrderDeliveryController@dispatch_order')->name('dispatch_order');
Route::post('complete_order', 'OrderDeliveryController@complete_order')->name('complete_order');

Route::post('check_uncheck_item', 'OrderDeliveryController@mark_unmark_item')->name('check_uncheck_item');

// SEARCH ROUTES
Route::get('search', 'SearchController@search_products')->name('search.products.storefront');
Route::get('autocomplete', 'SearchController@autocomplete')->name('search.autocomplete');

Route::resource('checkout', 'CheckOutController');
Route::resource('regions', 'RegionsController');
Route::resource('areas', 'AreasController');
Route::resource('customer_addresses', 'CustomerAddressesController');
Route::resource('orders', 'OrdersController');
Route::resource('delivery_team', 'DeliveryTeamController');

// Test Area
// Route::get('obfuscate', 'TestController@obfuscate');

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    // Point to table in database
    protected $table = 'regions';

    public function areas(){
        return $this->hasMany('App\Area');
    }
}

app/Http/Controllers/RegionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Region;

use Illuminate\Support\Str;

class RegionsController extends Controller
{

    /**
     * Create a new controller instance
     *
     * @return void
     */

    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        // Retrieve all regions from database
        $regions = Region::all();
        // print($regions);

        return view('regions/index')->with('regions', $regions);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('regions/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'region' => 'required'
        ]);
        // print($request);exit;

        // id 	region 	obfuscator 	user_id 	edited_by 	created_at 	updated_at

        // Get the user ID
        $user_id = auth()->user()->id;

        $obfuscator = Str::random(5);

        $region = new Region();

        $region->region = ucfirst($request->input('region'));
        $region->obfuscator = $obfuscator;
        $region->user_id = $user_id;

        if ($region->save()) {
            return redirect('regions')->with('success', 'Region has been added');
        } else {
            return redirect('regions')->with('error', 'Region has not been added');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // print($id);

        $obfuscator = $id;

        // Get region from database
        $region = Region::where('obfuscator', $obfuscator)->first();
        // print($region);

        return view('regions/show')->with('region', $region);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // print($id);

        $obfuscator = $id;

        // Retrieve region details
        $region = Region::where('obfuscator', $obfuscator)->first();
        // print($region);

        return view('regions/edit')->with('region', $region);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'region' => 'required'
        ]);
        // print($id);exit;

        $obfuscator = $id;

        // Get the user's ID
        $edited_by = auth()->user()->id;

        $region = Region::where('obfuscator', $obfuscator)->first();
        // print($region);exit;

        $region->region = ucfirst($request->input('region'));
        $region->edited_by = $edited_by;

        // Save changes to database
        if ($region->save()) {
            return redirect('regions')->with('success', 'Region has been updated successfully');
        } else {
            return redirect('regions')->with('error', 'Region has not been updated');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // print($id);

        $obfuscator = $id;

        // Retrieve record from database
        $region = Region::where('obfuscator', $obfuscator)->first();
        // print($region);

        $current_validity = $region->validity;
        // print($current_validity);

        $validity = '';

        // Change validity
        if ($current_validity == TRUE) {
            $validity = FALSE;

            $region->validity = $validity;

            // Save changes to database
            if ($region->save()) {
                return redirect('regions')->with('success', 'Region has been disabled');
            } else {
                return redirect('regions')->with('error', 'Region has not been disabled');
            }

        } else {
            $validity = TRUE;

            $region->validity = $validity;

            if ($region->save()) {
                return redirect('regions')->with('success', 'Region has been enabled');
            } else {
                return redirect('regions')->with('error', 'Region has not been enabled');
            }

        }

    }
}

resources/views/regions/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Add Region</h3>
        </div>
    </div>

    <hr />

    {{--  	id 	region 	obfuscator 	user_id 	edited_by 	created_at 	updated_at  --}}

    <div class="row">
        <div class="col-md-8 offset-md-2">
        <form method="POST" action="{{ route('regions.store') }}">

            {{ csrf_field() }}

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="Region">Region:</label>
                        <input type="text" name="region" class="form-control" required>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-dark btn-block">Submit</button>
                </div>
            </div>

        </form>
        </div>
    </div>

</div>

@endsection

resources/views/regions/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Edit Region</h3>
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <form method="POST" action="{{ route('regions.update', $region->obfuscator) }}">

                @method('PUT')
                {{ csrf_field() }}

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="Region">Region:</label>
                        <input type="text" name="region" class="form-control" value="{{ $region->region }}" required>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-dark btn-block">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

</div>

@endsection

resources/views/regions/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Regions</h3>
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-md-4 offset-md-4">
            <a href="{{ route('regions.create') }}" class="btn btn-dark btn-block">Add Region</a>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-10 offset-md-1">
            @if (count($regions) > 0)
                <div class="row">
                    @foreach ($regions as $region)
                        <div class="col-md-3 mt-3">
                            <a href="{{ route('regions.show', $region->obfuscator) }}">
                                <div class="card">
                                    <div class="card-body">
                                        {{ $region->region }}
                                    </div>
                                </div>
                            </a>
                        </div>
                    @endforeach
                </div>
            @else
                <p>No regions to display</p>
            @endif
        </div>
    </div>

</div>

@endsection

resources/views/regions/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Region Details</h3>
        </div>
    </div>

    <hr />

    {{-- id 	region 	obfuscator 	user_id 	edited_by 	created_at 	updated_at  --}}

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="card-text">Region:</p>
                        </div>
                        <div class="col-md-6">
                            <p class="card-text">{{ $region->region }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-6">
                    <a href="{{ route('regions.edit', $region->obfuscator) }}" class="btn btn-secondary btn-block">Edit</a>
                </div>
                <div class="col-md-6">
                    <form method="POST" action="{{ route('regions.destroy', $region->obfuscator) }}">
                        @method('DELETE')
                        {{ csrf_field() }}
                        @if ($region->validity == TRUE)
                            <button type="submit" class="btn btn-danger btn-block">Disable</button>
                        @else
                            <button type="submit" class="btn btn-success btn-block">Enable</button>
                        @endif

                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection