routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('product_categories', 'ProductCategoriesController');
Route::resource('sub_categories', 'ProductSubCategoriesController');
Route::resource('brands', 'BrandsController');
Route::resource('products', 'ProductsController');
Route::resource('markets', 'MarketsController');
Route::resource('vendors', 'VendorsController');
Route::resource('category', 'CategoryProductsController');

Route::resource('market', 'ShopMarketsController');

Route::get('/fruits', 'CategoryProductsController@show_fruits')->name('fruits');
Route::get('/vegetables', 'CategoryProductsController@show_vegetables')->name('vegetables');
Route::get('/meats', 'CategoryProductsController@show_meats')->name('meats');
Route::get('/potatoes', 'CategoryProductsController@show_potatoes')->name('potatoes');

// Markets
// Route::get('sessions', 'SessionsController');

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::resource('shop', 'ShopController');
Route::get('computers_network_eqpt', 'ShopController@ict_solutions')->name('comps_network_eqpt');
Route::get('power_solutions', 'ShopController@power_solutions')->name('power_solutions');
Route::get('security_solutions', 'ShopController@security_solutions')->name('security_solutions');

// Routes for products per category
Route::get('computers_network_eqpt/{identifier}', 'ShopController@ict_products')->name('comps_network_eqpt_products');
Route::get('power_solutions/{identifier}', 'ShopController@power_products')->name('power_products');
Route::get('security_solutions/{identifier}', 'ShopController@security_products')->name('security_products');

Auth::routes(['verified' => false]);

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::get('customer/sign_up', 'Customer\Auth\RegisterController@customerRegistrationForm')->name('customer.register');
Route::post('customer/register', 'Customer\Auth\RegisterController@create')->name('customer.create');
Route::get('customer/profile', 'CustomerProfileController@profile')->name('customer.profile');
Route::get('customer/profile/edit/{token}', 'CustomerProfileController@edit')->name('customer.profile.edit');
Route::put('customer/profile/update/{token}', 'CustomerProfileController@update')->name('customer.profile.update');

Route::prefix('/customer')->name('customer.')->namespace('Customer')->group(function () {

    // Route::get('/profile', function(){
    //     return view('customer/profile');
    // })->name('profile');


    // All the customer routes will be defined here...
    Route::namespace('Auth')->group(function () {

        // Login Routes
        Route::get('/login', 'LoginController@showLoginForm')->name('login');
        Route::post('/login', 'LoginController@login');
        Route::post('/logout', 'LoginController@logout')->name('logout');

        // Forgot Password Routes
        Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        // Reset Password Routes
        Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    });
});

// Store Front

Route::resource('items', 'ItemsController');

Route::post('cart-add', 'CartController@add')->name('cart.add');
Route::get('cart', 'CartController@cart')->name('cart');
Route::get('cart-clear', 'CartController@clear')->name('cart.clear');
Route::post('cart-increase-qty', 'CartController@cart_increase_qty')->name('cart.increase_qty');
Route::put('cart-update/{token}', 'CartController@update')->name('cart.update');
Route::post('update-cart', 'CartController@update_cart')->name('update.cart');

Route::get('sub_category_related_products', 'AjaxController@get_products_per_sub_category')->name('products_per_sub_category');
Route::get('category_related_sub_categories', 'AjaxController@get_sub_categories_per_category')->name('sub_categories_per_category');
Route::get('areas_per_region', 'AjaxController@areas_per_region')->name('areas_per_region');
Route::post('change_featured_status', 'AjaxController@change_featured_status');
Route::get('sub_categories_per_product_category', 'AjaxController@get_sub_categories_per_product_category')->name('sub_categories_per_product_category');

Route::get('add_icon', 'CategoryIconsController@add_icon')->name('category.add_icon');
Route::post('store_icon', 'CategoryIconsController@store_icon')->name('category.store_icon');

Route::get('successful_order', 'PagesController@order_success')->name('order.success');

// ORDER PROCESSING
Route::get('process_order/{token}', 'OrderDeliveryController@process_order')->name('process_order');
Route::post('process_order_delivery', 'OrderDeliveryController@process_order_delivery')->name('process_order_delivery');
Route::post('dispatch_order', 'OrderDeliveryController@dispatch_order')->name('dispatch_order');
Route::post('complete_order', 'OrderDeliveryController@complete_order')->name('complete_order');

Route::post('check_uncheck_item', 'OrderDeliveryController@mark_unmark_item')->name('check_uncheck_item');

// SEARCH ROUTES
Route::get('search', 'SearchController@search_products')->name('search.products.storefront');
Route::get('autocomplete', 'SearchController@autocomplete')->name('search.autocomplete');

Route::resource('checkout', 'CheckOutController');
Route::resource('regions', 'RegionsController');
Route::resource('areas', 'AreasController');
Route::resource('customer_addresses', 'CustomerAddressesController');
Route::resource('orders', 'OrdersController');
Route::resource('delivery_team', 'DeliveryTeamController');

// Test Area
// Route::get('obfuscate', 'TestController@obfuscate');

resources/views/inc/footer.blade.php
<footer class="bg-dark mt-5" style="position:relative; bottom:0; height: 260px;">
    <div class="container mt-3">
        <div class="row mt-3">
            <div class="col-md-4 mt-5">
                {{-- <h3 class="text-warning">
                    <i class="fas fa-drumstick-bite fa-3x text-warning"></i>
                </h3> --}}
                <h3 class="text-white">Chakula</h3>
                <p class="text-warning">Groceries and fresh produce delivered to your door step</p>
            </div>
            <div class="col-md-4 mt-5">
                <a href="" class="text-white">
                    <p>Customer Login</p>
                </a>
                <a href="" class="text-white">
                    <p>Terms of Use</p>
                </a>
                <a href="" class="text-white">
                    <p>Privacy Policy</p>
                </a>
            </div>
            <div class="col-md-4 mt-5">
                <p class="text-white"><i class="fas fa-phone-square-alt mr-3"></i> +256 700123456</p>
                <p class="text-white"><i class="fas fa-envelope mr-3"></i> info@example.com</p>
            </div>
        </div>
        <hr style="border border-white" />
        <p class="text-white text-center font-weight-bold" style="bottom:20px">
            &copy; 2021 Chakula. All rights reserved
        </p>
    </div>
</footer>

resources/views/inc/navbar.blade.php
<nav class="navbar navbar-dark sticky-top bg-light flex-md-nowrap p-0 shadow">
    <a class="navbar-brand text-warning col-md-3 col-lg-2 mr-0 px-3" href="{{ route('dashboard') }}" style="font-family: 'Comfortaa', cursive !important;">
        <h3>Chakula</h3>
    </a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation" style="margin-left:350px;">
      <span class="navbar-toggler-icon"></span>
    </button>

  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 sticky-top col-lg-2 d-md-block bg-secondary sidebar collapse" style="height: 100vh!important;">
        <div class="sidebar-sticky pt-3">
          <ul class="nav flex-column">
            @if (Auth::guard('web')->check())
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::guard('web')->user()->name }} (ADMIN) <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a href="" class="dropdown-item">Profile</a>
                        <a class="dropdown-item" href="#" onclick="event.preventDefault();document.querySelector('#logout-form').submit();">
                            Logout
                        </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display:none;">
                        @csrf
                    </form>
                    </div>
                </li>
            @endif
            <li class="nav-item">
              <a class="nav-link active text-warning" href="{{ route('dashboard') }}">
                <span data-feather="home"></span>
                Dashboard <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('markets.index') }}">
                    Markets
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('vendors.index') }}">
                    Vendors
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('orders.index') }}">
                    Orders
                </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-warning" href="{{ route('product_categories.index') }}">

                Product Categories
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-warning" href="{{ route('sub_categories.index') }}">

                Sub Categories
              </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('brands.index') }}">

                    Brands
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('products.index') }}">

                    Products
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('regions.index') }}">

                    Regions
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('areas.index') }}">

                    Areas
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-warning" href="{{ route('delivery_team.index') }}">
                    Delivery Team
                </a>
            </li>
          </ul>

        </div>
      </nav>

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
{{-- ============================================ --}}

resources/views/inc/navbar2.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand text-warning font_weight_600" href="{{ url('/') }}" style="font-family: 'Comfortaa', cursive !important;">
            <h3>Chakula</h3>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-5">
                <li class="nav-item">
                    <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('welcome') }}" style="font-family: 'Comfortaa', cursive !important;">Markets</a>
                </li>
            </ul>
            {{-- Right side of Navbar --}}
            <ul class="navbar-nav ml-auto">
                {{-- Authentication Links --}}
                {{-- @if (Auth::guard('web')->check())
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::guard('web')->user()->name }} (ADMIN) <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a href="{{ route('dashboard') }}" class="dropdown-item">Dashboard</a>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault();document.querySelector('#logout-form').submit();">
                                Logout
                            </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display:none;">
                            @csrf
                        </form>
                        </div>
                    </li>
                @endif --}}
                @if (Auth::guard('customer')->check())
                    <li class="nav-item dropdown">
                        <a id="customerDropdown" class="nav-link dropdown-toggle text_16 font-weight-bold" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre style="font-family: 'Comfortaa', cursive !important;">
                            {{ Auth::guard('customer')->user()->first_name }} <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="customerDropdown">
                            <a href="{{ route('customer.profile') }}" class="dropdown-item" style="font-family: 'Comfortaa', cursive !important;">Profile</a>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault();document.querySelector('#customer-logout-form').submit();" style="font-family: 'Comfortaa', cursive !important;">
                                Logout
                            </a>
                            <form id="customer-logout-form" action="{{ route('customer.logout') }}" method="POST" style="display:none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('customer.login') }}" style="font-family: 'Comfortaa', cursive !important;">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('customer.register') }}" style="font-family: 'Comfortaa', cursive !important;">Register</a>
                    </li>
                @endif
                <li class="nav-item">
                    <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('cart') }}" style="font-family: 'Comfortaa', cursive !important;"><i class="fas fa-shopping-cart text-warning"></i><span class="badge badge-pill badge-danger">{{ Cart::count() }}</span> Cart</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/inc/navbar3.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand text-warning font_weight_600 mr-5" href="{{ url('/') }}" style="font-family: 'Comfortaa', cursive !important;">
            <h3>Chakula</h3>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-5">
                <li class="nav-item">
                    <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('welcome') }}" style="font-family: 'Comfortaa', cursive !important;">Markets</a>
                </li>
            </ul>
            {{-- Right side of Navbar --}}
            <ul class="navbar-nav ml-auto">
                {{-- Authentication Links --}}
                {{-- @if (Auth::guard('web')->check())
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::guard('web')->user()->name }} (ADMIN) <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a href="{{ route('dashboard') }}" class="dropdown-item">Dashboard</a>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault();document.querySelector('#logout-form').submit();">
                                Logout
                            </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display:none;">
                            @csrf
                        </form>
                        </div>
                    </li>
                @endif --}}
                @if (Auth::guard('customer')->check())
                    <li class="nav-item dropdown">
                        <a id="customerDropdown" class="nav-link dropdown-toggle text_16 font-weight-bold" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre style="font-family: 'Expletus Sans', cursive !important;">
                            {{ Auth::guard('customer')->user()->first_name }} <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="customerDropdown">
                            <a href="{{ route('customer.profile') }}" class="dropdown-item" style="font-family: 'Expletus Sans', cursive !important;">Profile</a>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault();document.querySelector('#customer-logout-form').submit();" style="font-family: 'Expletus Sans', cursive !important;">
                                Logout
                            </a>
                            <form id="customer-logout-form" action="{{ route('customer.logout') }}" method="POST" style="display:none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @else
                    <li class="nav-item">
                        <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('customer.login') }}" style="font-family: 'Expletus Sans', cursive !important;">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('customer.register') }}" style="font-family: 'Expletus Sans', cursive !important;">Register</a>
                    </li>
                @endif
                <li class="nav-item">
                    <a class="nav-link text-primary text_16 font-weight-bold" href="{{ route('cart') }}" style="font-family: 'Expletus Sans', cursive !important;"><i class="fas fa-shopping-cart text-warning"></i><span class="badge badge-pill badge-danger">{{ Cart::count() }}</span> Cart</a>
                </li>
            </ul>
        </div>
    </div>
</nav>