routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('product_categories', 'ProductCategoriesController');
Route::resource('sub_categories', 'ProductSubCategoriesController');
Route::resource('brands', 'BrandsController');
Route::resource('products', 'ProductsController');
Route::resource('markets', 'MarketsController');
Route::resource('vendors', 'VendorsController');
Route::resource('category', 'CategoryProductsController');

Route::resource('market', 'ShopMarketsController');

Route::get('/fruits', 'CategoryProductsController@show_fruits')->name('fruits');
Route::get('/vegetables', 'CategoryProductsController@show_vegetables')->name('vegetables');
Route::get('/meats', 'CategoryProductsController@show_meats')->name('meats');
Route::get('/potatoes', 'CategoryProductsController@show_potatoes')->name('potatoes');

// Markets
// Route::get('sessions', 'SessionsController');

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::resource('shop', 'ShopController');
Route::get('computers_network_eqpt', 'ShopController@ict_solutions')->name('comps_network_eqpt');
Route::get('power_solutions', 'ShopController@power_solutions')->name('power_solutions');
Route::get('security_solutions', 'ShopController@security_solutions')->name('security_solutions');

// Routes for products per category
Route::get('computers_network_eqpt/{identifier}', 'ShopController@ict_products')->name('comps_network_eqpt_products');
Route::get('power_solutions/{identifier}', 'ShopController@power_products')->name('power_products');
Route::get('security_solutions/{identifier}', 'ShopController@security_products')->name('security_products');

Auth::routes(['verified' => false]);

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::get('customer/sign_up', 'Customer\Auth\RegisterController@customerRegistrationForm')->name('customer.register');
Route::post('customer/register', 'Customer\Auth\RegisterController@create')->name('customer.create');
Route::get('customer/profile', 'CustomerProfileController@profile')->name('customer.profile');
Route::get('customer/profile/edit/{token}', 'CustomerProfileController@edit')->name('customer.profile.edit');
Route::put('customer/profile/update/{token}', 'CustomerProfileController@update')->name('customer.profile.update');

Route::prefix('/customer')->name('customer.')->namespace('Customer')->group(function () {

    // Route::get('/profile', function(){
    //     return view('customer/profile');
    // })->name('profile');


    // All the customer routes will be defined here...
    Route::namespace('Auth')->group(function () {

        // Login Routes
        Route::get('/login', 'LoginController@showLoginForm')->name('login');
        Route::post('/login', 'LoginController@login');
        Route::post('/logout', 'LoginController@logout')->name('logout');

        // Forgot Password Routes
        Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        // Reset Password Routes
        Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    });
});

// Store Front

Route::resource('items', 'ItemsController');

Route::post('cart-add', 'CartController@add')->name('cart.add');
Route::get('cart', 'CartController@cart')->name('cart');
Route::get('cart-clear', 'CartController@clear')->name('cart.clear');
Route::post('cart-increase-qty', 'CartController@cart_increase_qty')->name('cart.increase_qty');
Route::put('cart-update/{token}', 'CartController@update')->name('cart.update');
Route::post('update-cart', 'CartController@update_cart')->name('update.cart');

Route::get('sub_category_related_products', 'AjaxController@get_products_per_sub_category')->name('products_per_sub_category');
Route::get('category_related_sub_categories', 'AjaxController@get_sub_categories_per_category')->name('sub_categories_per_category');
Route::get('areas_per_region', 'AjaxController@areas_per_region')->name('areas_per_region');
Route::post('change_featured_status', 'AjaxController@change_featured_status');
Route::get('sub_categories_per_product_category', 'AjaxController@get_sub_categories_per_product_category')->name('sub_categories_per_product_category');

Route::get('add_icon', 'CategoryIconsController@add_icon')->name('category.add_icon');
Route::post('store_icon', 'CategoryIconsController@store_icon')->name('category.store_icon');

Route::get('successful_order', 'PagesController@order_success')->name('order.success');

// ORDER PROCESSING
Route::get('process_order/{token}', 'OrderDeliveryController@process_order')->name('process_order');
Route::post('process_order_delivery', 'OrderDeliveryController@process_order_delivery')->name('process_order_delivery');
Route::post('dispatch_order', 'OrderDeliveryController@dispatch_order')->name('dispatch_order');
Route::post('complete_order', 'OrderDeliveryController@complete_order')->name('complete_order');

Route::post('check_uncheck_item', 'OrderDeliveryController@mark_unmark_item')->name('check_uncheck_item');

// SEARCH ROUTES
Route::get('search', 'SearchController@search_products')->name('search.products.storefront');
Route::get('autocomplete', 'SearchController@autocomplete')->name('search.autocomplete');

Route::resource('checkout', 'CheckOutController');
Route::resource('regions', 'RegionsController');
Route::resource('areas', 'AreasController');
Route::resource('customer_addresses', 'CustomerAddressesController');
Route::resource('orders', 'OrdersController');
Route::resource('delivery_team', 'DeliveryTeamController');

// Test Area
// Route::get('obfuscate', 'TestController@obfuscate');

app/Market.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Market extends Model
{
    // Point to table in database
    protected $table = 'markets';

    public function vendors()
    {
        return $this->hasMany('App\Vendor', 'vendor_id', 'id');
    }

    public function orders()
    {
        return $this->hasMany('App\Order', 'market_id', 'id');
    }
 
}

app/Http/Controllers/MarketsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Market;

use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Str;

use Auth;

class MarketsController extends Controller
{

    /**
     * Create a new controller instance
     *
     * @return void
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $markets = Market::paginate(10);

        return view('markets.index')->with('markets', $markets);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('markets.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'market' => 'required'
        ]);

        // Get the user ID
        $user_id = auth()->user()->id;

        // Generate obfuscator
        $obfuscator = Str::random(5);
        // print($obfuscator);exit;

        // print($request);
        // exit;

        if ($request->hasFile('picture')) {

            // Get file name with extension
            $fileNameWithExt = $request->file('picture')->getClientOriginalName();

            // Get file name only
            $filename = pathinfo($fileNameWithExt, PATHINFO_FILENAME);

            // Get the file extension only
            $extension = $request->file('picture')->getClientOriginalExtension();

            // Create file name to store
            $fileNameToStore = $filename . '_' . time() . '.' . $extension;

            // Upload image
            $path = $request->file('picture')->storeAs('public/uploads/markets', $fileNameToStore);
        } else {

            $fileNameToStore = 'nofile.png';
        }

        // Save market to database
        $market = new Market();

        $market->market = ucwords($request->input('market'));
        $market->image = $fileNameToStore;
        $market->obfuscator = $obfuscator;
        $market->image_url = $request->input('image_url');

        // Save record to database
        if ($market->save()) {
            return redirect('markets')->with('success', 'The market has been added');;
        } else {
            return redirect('markets')->with('error', 'The market has not been added');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // print($id);

        $market = Market::where('obfuscator', $id)->first();
        // print($market);

        return view('markets.show')->with(['market' => $market]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $obfuscator = $id;

        // Retrieve category from database
        $market = Market::where('obfuscator', $obfuscator)->first();
        // print($product_category);

        return view('markets/edit')->with('market', $market);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'market' => 'required'
        ]);

        $market_id = $id;

        if ($request->hasFile('picture')) {

            // get file name with extension
            $fileNameWithExt = $request->file('picture')->getClientOriginalName();

            // Get file name only
            $filename = pathinfo($fileNameWithExt, PATHINFO_FILENAME);

            // Get the file extension only
            $extension = $request->file('picture')->getClientOriginalExtension();

            // Create file name to store
            $fileNameToStore = $filename . '_' . time() . '.' . $extension;

            // Upload image
            $path = $request->file('picture')->storeAs('public/uploads/categories', $fileNameToStore);

            // {{-- id 	category 	category_image 	user_id 	edited_by 	created_at 	updated_at --}}

            $market = Market::where('obfuscator', $market_id)->first();

            // Delete current picture from database/ storage
            $picture = $market->image;

            if (Storage::delete('public/uploads/markets/' . $picture)) {

                $market->market = ucfirst($request->input('market'));
                $market->image = $fileNameToStore;
                $market->image_url = $request->input('image_url');

                if ($market->save()) {
                    return redirect('markets')->with('success', 'Market details have been updated');
                } else {
                    return redirect('market')->with('error', 'Market details have not been updated');
                }
            }
        } else {

            $fileNameToStore = 'nofile.pdf';

            $market = Market::where('obfuscator', $market_id)->first();

            $market->market = ucfirst($request->input('market'));
            $market->image = $fileNameToStore;
            $market->image_url = $request->input('image_url');

            if ($market->save()) {
                return redirect('markets')->with('success', 'Market details have been updated');
            } else {
                return redirect('markets')->with('error', 'Market details have not been updated');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $obfuscator = $id;

        // Retrieve record
        $market = Market::where('obfuscator', $obfuscator)->first();

        if ($market) {
            if ($market->delete()) {
                return redirect('markets')->with('success', 'Market details have been deleted');
            } else {
                return redirect('markets')->with('error', 'Market details have not been deleted');
            }
        }
    }
}

resources/views/markets/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Add Market</h3>
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <form method="POST" action="{{ route('markets.store') }}" enctype="multipart/form-data">

                {{ csrf_field() }}

                <div class="form-group">
                    <label for="Market">Market:</label>
                    <input type="text" name="market" class="form-control" required />
                </div>

                <div class="form-group">
                    <label for="categoryImage">Upload Image:</label>
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="fileUpload" name="picture">
                            <label class="custom-file-label" for="fileUpload">Choose File</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="Market">Image URL:</label>
                    <input type="text" name="image_url" class="form-control" required />
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-dark btn-block">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

</div>

<script type="text/javascript">

    $(document).ready(function(){

        var fileLabel = $('.custom-file-label');

        $('.custom-file-input').on('change', function(){
            var fileName = $(this).val();

            fileLabel.text(fileName);
        });

    });

</script>
@endsection

resources/views/markets/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Edit Market Details</h3>
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <form method="POST" action="{{ route('markets.update', $market->obfuscator) }}" enctype="multipart/form-data">

                @method('PUT')
                {{ csrf_field() }}

                <div class="form-group">
                    <label for="Market">Market:</label>
                    <input type="text" name="market" class="form-control" value="{{ $market->market }}" required />
                </div>

                <div class="form-group">
                    <label for="categoryImage">Upload Image:</label>
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="fileUpload" name="picture">
                            <label class="custom-file-label" for="fileUpload">Choose File</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="Market">Image URL:</label>
                    <input type="text" name="image_url" class="form-control" value="{{ $market->image_url }}" required />
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-dark btn-block">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

</div>

<script type="text/javascript">

    $(document).ready(function(){

        var fileLabel = $('.custom-file-label');

        $('.custom-file-input').on('change', function(){
            var fileName = $(this).val();

            fileLabel.text(fileName);
        });

    });

</script>
@endsection

resources/views/markets/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Markets</h3>
        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-md-4 offset-md-4">
            <a href="{{ route('markets.create') }}" class="btn btn-dark btn-block">Add Market</a>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-10 offset-md-1">
            @if ($markets)
                <div class="row">
                    @foreach($markets as $market)
                        <div class="col-md-4">
                            <div class="card" style="">
                                <img src="{{ $market->image_url }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <h5 class="card-title">{{ $market->market }}</h5>
                                    {{-- <a href="#" class="btn btn-primary">Go somewhere</a> --}}
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col-md-6">
                                    <a href="{{ route('markets.edit', $market->obfuscator) }}" class="btn btn-secondary btn-block">Edit</a>
                                </div>
                                <div class="col-md-6">
                                    <form method="POST" action="{{ route('markets.destroy', $market->obfuscator) }}">
                                        @method('DELETE')
                                        {{csrf_field()}}
                                        <button type="submit" class="btn btn-danger btn-block">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                <div class="row">
                    <div class="col-md-4 offset-md-4">
                        {{ $markets->links() }}
                    </div>
                </div>
            @else
                <p>No markets to display</p>
            @endif
        </div>
    </div>

</div>

@endsection

resources/views/markets/show.blade.php
@extends('layouts.app')

@section('content')
<div class="jumbotron bg-primary rounded-0" style="margin-top:-20px;height:200px;" id="welcomeJumbo">
    <div class="row">
        <div class="col-md-6 text-light mt-5">
        <h1>{{ $market->market }}</h1>
        </div>
    </div>
</div>

<div class="container">
    <h2>Products sold</h2>
    
</div>
@endsection