routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('product_categories', 'ProductCategoriesController');
Route::resource('sub_categories', 'ProductSubCategoriesController');
Route::resource('brands', 'BrandsController');
Route::resource('products', 'ProductsController');
Route::resource('markets', 'MarketsController');
Route::resource('vendors', 'VendorsController');
Route::resource('category', 'CategoryProductsController');

Route::resource('market', 'ShopMarketsController');

Route::get('/fruits', 'CategoryProductsController@show_fruits')->name('fruits');
Route::get('/vegetables', 'CategoryProductsController@show_vegetables')->name('vegetables');
Route::get('/meats', 'CategoryProductsController@show_meats')->name('meats');
Route::get('/potatoes', 'CategoryProductsController@show_potatoes')->name('potatoes');

// Markets
// Route::get('sessions', 'SessionsController');

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::resource('shop', 'ShopController');
Route::get('computers_network_eqpt', 'ShopController@ict_solutions')->name('comps_network_eqpt');
Route::get('power_solutions', 'ShopController@power_solutions')->name('power_solutions');
Route::get('security_solutions', 'ShopController@security_solutions')->name('security_solutions');

// Routes for products per category
Route::get('computers_network_eqpt/{identifier}', 'ShopController@ict_products')->name('comps_network_eqpt_products');
Route::get('power_solutions/{identifier}', 'ShopController@power_products')->name('power_products');
Route::get('security_solutions/{identifier}', 'ShopController@security_products')->name('security_products');

Auth::routes(['verified' => false]);

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::get('customer/sign_up', 'Customer\Auth\RegisterController@customerRegistrationForm')->name('customer.register');
Route::post('customer/register', 'Customer\Auth\RegisterController@create')->name('customer.create');
Route::get('customer/profile', 'CustomerProfileController@profile')->name('customer.profile');
Route::get('customer/profile/edit/{token}', 'CustomerProfileController@edit')->name('customer.profile.edit');
Route::put('customer/profile/update/{token}', 'CustomerProfileController@update')->name('customer.profile.update');

Route::prefix('/customer')->name('customer.')->namespace('Customer')->group(function () {

    // Route::get('/profile', function(){
    //     return view('customer/profile');
    // })->name('profile');


    // All the customer routes will be defined here...
    Route::namespace('Auth')->group(function () {

        // Login Routes
        Route::get('/login', 'LoginController@showLoginForm')->name('login');
        Route::post('/login', 'LoginController@login');
        Route::post('/logout', 'LoginController@logout')->name('logout');

        // Forgot Password Routes
        Route::get('/password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('/password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');

        // Reset Password Routes
        Route::get('/password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('/password/reset', 'ResetPasswordController@reset')->name('password.update');
    });
});

// Store Front

Route::resource('items', 'ItemsController');

Route::post('cart-add', 'CartController@add')->name('cart.add');
Route::get('cart', 'CartController@cart')->name('cart');
Route::get('cart-clear', 'CartController@clear')->name('cart.clear');
Route::post('cart-increase-qty', 'CartController@cart_increase_qty')->name('cart.increase_qty');
Route::put('cart-update/{token}', 'CartController@update')->name('cart.update');
Route::post('update-cart', 'CartController@update_cart')->name('update.cart');

Route::get('sub_category_related_products', 'AjaxController@get_products_per_sub_category')->name('products_per_sub_category');
Route::get('category_related_sub_categories', 'AjaxController@get_sub_categories_per_category')->name('sub_categories_per_category');
Route::get('areas_per_region', 'AjaxController@areas_per_region')->name('areas_per_region');
Route::post('change_featured_status', 'AjaxController@change_featured_status');
Route::get('sub_categories_per_product_category', 'AjaxController@get_sub_categories_per_product_category')->name('sub_categories_per_product_category');

Route::get('add_icon', 'CategoryIconsController@add_icon')->name('category.add_icon');
Route::post('store_icon', 'CategoryIconsController@store_icon')->name('category.store_icon');

Route::get('successful_order', 'PagesController@order_success')->name('order.success');

// ORDER PROCESSING
Route::get('process_order/{token}', 'OrderDeliveryController@process_order')->name('process_order');
Route::post('process_order_delivery', 'OrderDeliveryController@process_order_delivery')->name('process_order_delivery');
Route::post('dispatch_order', 'OrderDeliveryController@dispatch_order')->name('dispatch_order');
Route::post('complete_order', 'OrderDeliveryController@complete_order')->name('complete_order');

Route::post('check_uncheck_item', 'OrderDeliveryController@mark_unmark_item')->name('check_uncheck_item');

// SEARCH ROUTES
Route::get('search', 'SearchController@search_products')->name('search.products.storefront');
Route::get('autocomplete', 'SearchController@autocomplete')->name('search.autocomplete');

Route::resource('checkout', 'CheckOutController');
Route::resource('regions', 'RegionsController');
Route::resource('areas', 'AreasController');
Route::resource('customer_addresses', 'CustomerAddressesController');
Route::resource('orders', 'OrdersController');
Route::resource('delivery_team', 'DeliveryTeamController');

// Test Area
// Route::get('obfuscate', 'TestController@obfuscate');

app/Product.php
<?php

namespace App;

use Gloudemans\Shoppingcart\Contracts\Buyable;
use Illuminate\Database\Eloquent\Model;

class Product extends Model implements Buyable
{
    // Point to table in database
    protected $table = 'products';

    public function category(){
        return $this->belongsTo('App\ProductCategory', 'category_id', 'id');
    }

    public function brand(){
        return $this->belongsTo('App\Brand');
    }

    // Implement Functions of Buyable Interface

    public function getBuyableIdentifier($options = null)
    {
        return $this->id;
    }

    public function getBuyableDescription($options = null)
    {
        return $this->product_name;
    }

    public function getBuyablePrice($options = null)
    {
        return $this->price;
    }

    public function getBuyableWeight($options = null)
    {
        return $this->weight;
    }

    public function orders(){
        return $this->belongsToMany('App\Order', 'order_product', 'product_id', 'order_id');
    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\ProductCategory;
use App\Brand;
use App\ProductSubCategory;
use App\StockTracking;

use Illuminate\Support\Facades\Storage;

use Illuminate\Support\Str;

class ProductsController extends Controller
{

    /**
     * Create a new controller instance
     *
     * @return void
     */

    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        // Retrieve all products from database
        $products = Product::all();
        // print($products);

        return view('products/index')->with('products', $products);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // retrieve all categories from database
        $product_categories = ProductCategory::all();
        // print($product_categories);

        // Retrieve all sub categories from database
        $sub_categories = ProductSubCategory::all();
        // print($sub_categories);

        // Retrieve all brands from database
        $brands = Brand::all();
        // print($brands);

        return view('products/create')->with(['product_categories' => $product_categories, 'brands' => $brands, 'sub_categories' => $sub_categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'product_name' => 'required',
            'price' => 'required',
            'product_category' => 'required',
            'sub_category' => 'required',
        ]);
        // print($request);exit;

        // Get the user ID
        $user_id = auth()->user()->id;

        $obfuscator = Str::random(5);

        if ($request->hasFile('picture')) {

            // Get file name with extension
            $fileNameWithExt = $request->file('picture')->getClientOriginalName();

            // Get file name only
            $filename = pathinfo($fileNameWithExt, PATHINFO_FILENAME);

            // Get the file extension only
            $extension = $request->file('picture')->getClientOriginalExtension();

            // Create file name to store
            $fileNameToStore = $filename.'_'.time().'.'.$extension;

            // Upload image
            $path = $request->file('picture')->storeAs('public/uploads/products', $fileNameToStore);

        } else {

            $fileNameToStore = 'nofile.pdf';

        }

        $stock_tracking = $request->input('track_stock');
        $track_stock = FALSE;
        if ($stock_tracking == 'Yes') {
            $track_stock = TRUE;
        } else{
            $track_stock = FALSE;
        }

        // STEPS:

        // 1. Save product information to database
        // 2. Retrieve id of saved product after insertion into database
        // 3. Record initial stock if stock is to be tracked
        // 4. Retrieve id of stock level/ record after insertion into database
        // 5. Find the newly inserted product.
        // 6. Update record of product with stock_tracking_id to ensure stock is monitored

        // id 	product_name 	product_image 	price 	track_stock 	description 	category_id 	user_id 	edited_by 	stock_tracking_id 	brand_id 	created_at 	updated_at

        $product = new Product();

        $product->product_name = ucfirst($request->input('product_name'));
        $product->product_image = $fileNameToStore;
        $product->price = $request->input('price');
        $product->description = 'Test description';
        $product->image_url = $request->input('image_url');
        $product->category_id = $request->input('product_category');
        $product->sub_category_id = $request->input('sub_category');
        $product->track_stock = FALSE;
        $product->user_id = $user_id;
        $product->obfuscator = $obfuscator;

        if ($product->save()) {
            return redirect('products')->with('success', 'The product has been inserted');
        } else {
            return redirect('products')->with('error', 'The product has not been inserted');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // print($id);

        $obfuscator = $id;

        // Get product from database
        $product = Product::where('obfuscator', $obfuscator)->first();
        // print($product->brand);

        $category_id = $product->category_id;
        $brand_id = $product->brand_id;

        // Get the category
        $category = ProductCategory::find($category_id);
        // print($category);

        // Get the brand
        $brand = Brand::find($brand_id);
        // print($brand);

        return view('products/show')->with(['product' => $product, 'category' => $category, 'brand' => $brand]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // print($id);

        $obfuscator = $id;

        // Retrieve product details
        $product = Product::where('obfuscator', $obfuscator)->first();
        // print($product->category_id);

        $category_id = $product->category_id;
        $brand_id = $product->brand_id;

        // Retrieve product's category
        $product_category = ProductCategory::find($category_id);
        // print($product_category);

        // Retrieve product's brand
        $product_brand = Brand::find($brand_id);
        // print($product_brand);


        // Retrieve all categories
        $categories = ProductCategory::all();
        // print($categories);

        // Retrieve all brands
        $brands = Brand::all();
        // print($brands);

        // Retrieve stock details
        $stock_tracking = StockTracking::find($product->stock_tracking_id);
        // print($stock_tracking);

        return view('products/edit')->with(['product' => $product, 'product_category' => $product_category, 'product_brand' => $product_brand, 'categories' => $categories, 'brands' => $brands, 'stock_tracking' => $stock_tracking]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'product_name' => 'required',
            'price' => 'required',
            'product_category' => 'required',
            'brand' => 'required',
            'product_description' => 'required'
        ]);
        // print($id);
        // print($request);exit;

        $obfuscator = $id;

        // Get the user's ID
        $edited_by = auth()->user()->id;

        if ($request->hasFile('picture')) {

            // Get file name with extension
            $fileNameWithExt = $request->file('picture')->getClientOriginalName();

            // Get file name only
            $filename = pathinfo($fileNameWithExt, PATHINFO_FILENAME);

            // Get the file extension only
            $extension = $request->file('picture')->getClientOriginalExtension();

            // Create file name to store
            $fileNameToStore = $filename.'_'.time().'.'.$extension;

            // Upload image
            $path = $request->file('picture')->storeAs('public/uploads/products', $fileNameToStore);

            // id 	product_name 	product_image 	price 	track_stock 	description 	category_id 	user_id 	edited_by 	stock_tracking_id 	brand_id 	created_at 	updated_at

            $product = Product::where('obfuscator', $obfuscator)->first();

            // To be added later:
                // 1. Check if file exists and delete before making changes

                $product->product_name = ucfirst($request->input('product_name'));
                $product->product_image = $fileNameToStore;
                $product->price = $request->input('price');
                $product->description = ucfirst($request->input('product_description'));
                $product->image_url = $request->input('image_url');
                $product->category_id = $request->input('product_category');
                // $product->brand_id = $request->input('brand');
                $product->edited_by = $edited_by;

                if ($product->save()) {
                    return redirect('products')->with('success', 'Product details have been updated');
                } else {
                    return redirect('products')->with('error', 'Product details have not been updated');
                }


        } else {

            $fileNameToStore = 'nofile.pdf';

            $product = Product::where('obfuscator', $obfuscator)->first();

            $product->product_name = ucfirst($request->input('product_name'));
            $product->price = $request->input('price');
            $product->description = ucfirst($request->input('product_description'));
            $product->category_id = $request->input('product_category');
            $product->brand_id = $request->input('brand');
            $product->edited_by = $edited_by;

            if ($product->save()) {
                return redirect('products')->with('success', 'Product details have been updated');
            } else {
                return redirect('products')->with('error', 'Product details have not been updated');
            }

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Add Product</h3>
        </div>
    </div>

    <hr />

    {{-- id 	product_name 	product_image 	price 	track_stock 	description 	category_id 	user_id 	edited_by 	stock_tracking_id 	brand_id 	created_at 	updated_at  --}}

    <div class="row">
        <div class="col-md-10 offset-md-1">
            <form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data">

                {{ csrf_field() }}

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="productName">Product Name:</label>
                            <input type="text" name="product_name" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label for="productImage">Product Image:</label>
                            <div class="input-group mb-3">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="fileUpload" name="picture">
                                    <label class="custom-file-label" for="fileUpload">Choose File</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-12">
                            <label for="">Image URL:</label>
                            <input type="text" name="image_url" class="form-control" />
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="Price">Price:</label>
                            <input type="text" name="price" class="form-control">
                        </div>
                        <div class="col-md-6">
                            <label for="productCategory">Product Category:</label>
                            <select name="product_category" class="custom-select" id="productCategory">
                                <option selected disabled>Choose...</option>
                                @if ($product_categories)
                                    @foreach ($product_categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->category }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                        {{-- <div class="col-md-4">
                            <label for="Brand">Brand:</label>
                            <select name="brand" class="custom-select">
                                <option selected disabled>Choose...</option>
                                @if ($brands)
                                    @foreach($brands as $brand)
                                        <option value="{{ $brand->id }}">{{ $brand->brand }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div> --}}
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="subCategory">Sub Category</label>
                            <select name="sub_category" class="custom-select" id="subCategory">
                                <option selected disabled>Choose...</option>
                                @if ($sub_categories)
                                    @foreach ($sub_categories as $sub_category)
                                        <option value="{{ $sub_category->id }}">{{ $sub_category->sub_category }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                        {{-- <div class="col-md-6">
                            <label for="trackStock">Track Stock?</label>
                            <select name="track_stock" class="custom-select">
                                <option disabled selected>Choose...</option>
                                <option value="Yes">Yes</option>
                                <option value="No">No</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <label for="Stock">Initial Stock</label>
                            <input type="text" name="initial_stock" class="form-control">
                        </div> --}}
                    </div>
                </div>

                {{-- <div class="form-group">
                    <label for="productDescription">Product Description:</label>
                    <textarea name="product_description" class="form-control" id="editor1" rows="5"></textarea>
                </div> --}}

                <div class="row">
                    <div class="col-md-12">
                        <button class="btn btn-dark btn-block">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

</div>

<script type="text/javascript">

    $(document).ready(function(){

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $('#productCategory').on('change', function(){

            let selected_category = $('#productCategory option:selected').val();
            // console.log(selected_category);

            $('#subCategory option').remove();

            $.ajax({
                method: 'GET',
                url: '/sub_categories_per_product_category',
                data: {category_id: selected_category},
                dataType: 'JSON',
                success: function(data){
                    // console.log(data);
                    data.forEach(element => {
                        var sub_category_name = element['sub_category'];
                        var sub_category_id = element['id'];

                        $('#subCategory').append('<option value="'+ sub_category_id +'">' + sub_category_name + '</option>');
                    });
                },
                error: function(data){
                    // console.log(data);
                }
            });

        });

        var fileLabel = $('.custom-file-label');

        $('.custom-file-input').on('change', function(){
            var fileName = $(this).val();

            fileLabel.text(fileName);
        });

    });

</script>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="jumbotron bg-primary rounded-0" style="margin-top:-30px;height:250px;" id="welcomeJumbo">
        <div class="row mt-5">
            <div class="col-md-4 text-light mt-5">
                <h3>Products</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">

        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-md-4 offset-md-4">
            <a href="{{ route('products.create') }}" class="btn btn-dark btn-block">
                Add Product
            </a>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-md-10 offset-md-1">
            @if ($products)
                <div class="row">
                    @foreach ($products as $product)
                        <div class="col-md-3 mt-3">
                            <a href="{{ route('products.show', $product->obfuscator) }}">
                                <div class="card border-0 shadow p-3 mb-5 bg-white rounded" style="">
                                    <img src="{{ $product->image_url }}" class="card-img-top" alt="...">
                                    <div class="card-body">
                                      <h5 class="card-title">{{ $product->product_name }}</h5>
                                      {{-- <a href="#" class="btn btn-primary">Go somewhere</a> --}}
                                    </div>
                                </div>
                            </a>
                        </div>
                    @endforeach
                </div>
            @else
                <p>No products to display</p>
            @endif
        </div>
    </div>

</div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 offset-md-3 text-center">
            <h3>Product Details</h3>
        </div>
    </div>

    <hr />

    {{-- id 	product_name 	product_image 	price 	track_stock 	description 	category_id 	user_id 	edited_by 	stock_tracking_id 	brand_id 	obfuscator 	created_at 	updated_at  --}}

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="row mt-3 mb-3">
                <div class="col-md-6">
                    <a href="{{ route('products.edit', $product->obfuscator) }}" class="btn btn-secondary btn-block">Edit</a>
                </div>
                <div class="col-md-6">
                    <form method="POST" action="{{ route('products.destroy', $product->obfuscator) }}">
                        @method('DELETE')
                        {{ csrf_field() }}
                        @if ($product->available == TRUE)
                            <button type="submit" class="btn btn-danger btn-block">Change Status to Not Available</button>
                        @else
                            <button type="submit" class="btn btn-danger btn-block">Change Status to Available</button>
                        @endif
                    </form>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="card-text font-weight-bold">Product:</p>
                        </div>
                        <div class="col-md-6">
                            <p class="card-text">{{ $product->product_name }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p class="card-text font-weight-bold">Product Image:</p>
                        </div>
                        <div class="col-md-6">
                            <img src="{{ asset('../storage/uploads/products/'.$product->product_image) }}" alt="" class="img-fluid">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p class="card-text font-weight-bold">Price:</p>
                        </div>
                        <div class="col-md-6">
                            <p class="card-text">UGX {{ $product->price }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p class="card-text font-weight-bold">Stock Tracking:</p>
                        </div>
                        <div class="col-md-6">
                            @if ($product->track_stock == TRUE)
                                <p class="card-text">Yes</p>
                            @else
                                <p class="card-text">No</p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p class="card-text font-weight-bold">Category:</p>
                        </div>
                        <div class="col-md-6">
                            <p class="card-text">{{ $category->category }}</p>
                        </div>
                    </div>
                    @if ($product->brand !== NULL || $product->brand !== '')
                        <div class="row">
                            <div class="col-md-6">
                                <p class="card-text font-weight-bold">Brand:</p>
                            </div>
                            <div class="col-md-6">
                                <p class="card-text">{{ $product->brand->brand }}</p>
                            </div>
                        </div>
                    @endif
                </div>
            </div>{{-- end of .card --}}
            <div class="row mt-3">
                <div class="col-md-12">
                    <label for="Description" class="font-weight-bold">Description:</label>
                    {!! $product->description !!}
                </div>
            </div>

        </div>
    </div>

</div>

@endsection